# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MiningPoolHub' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MiningPoolHub
  pod 'DateToolsSwift'
  pod 'Kingfisher'
  pod 'ObjectMapper'
  pod 'MiningPoolHub-Swift'
  pod 'SwiftCharts', '~> 0.6.1'

  target 'MiningPoolHubTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MiningPoolHubUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
